### ISSUE TITLE
Scrolling animation for "To Top" button

### ISSUE THREAD

**Issue by JadeMaveric** [ieee-gec-sb/Project-Oslo#17]
**Is your feature request related to a problem? Please describe.**
Currently pressing the "To Top" button directly jumps to the top of the page. We can do better than this.

**Describe the solution you'd like**
Adding a scrolling animation that gradually scrolls to the top would look much better.

**Additional context**
I've already submitted a fix 6404e2c8d33f3c2383f5196cd199170de44c585f. Incorporating it into other pages, as well as the template page should be trivial.

**Comment by kevinam99** [comment]
Please notify once it's done and then close this issue.

**Comment by JadeMaveric** [comment]
Commited changes across the site 72459baee8cc60f6a863dd785966d0ed8ff5e53a
